# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0c4328fd98cfc4e7aa86275516c5307a4d188809b3d579034af1a12126667676743587bac4a5f8736839b5e32ae0950a6ad7e52c99d556b9f4b9abbdb04ae65

test:
  secret_key_base: 14960de842615d42c38bef4272c69315270f928a9cd3c3626f075f1310d09e1a68168b4fed01407eed9e041bbfb35fe55072802be8ceda6fc993bf6bccfc1f60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
